apiVersion: apps/v1
kind: Deployment
metadata:
  name: autobuild-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: autobuild-deployment
  template:
    metadata:
      labels:
        app: autobuild-deployment
    spec:
      containers:
      - name: autobuild-deployment
        image: kartikeya24/autobuildimageforextractingemailonk8s:latest
        command: ["python3", "/AutoBuildImage-ExtractingEmailsOnK8s/src/main.py"]
        env:
        - name: GITHUB_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-secrets
              key: GITHUB_ACCESS_TOKEN
        - name: DOCKER_USERNAME
          valueFrom:
            secretKeyRef:
              name: dockerhub-secrets
              key: DOCKER_USERNAME
        - name: DOCKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dockerhub-secrets
              key: DOCKER_PASSWORD
      imagePullSecrets:
      - name: regcred
